### ISSUE TITLE
[Bug] Configuration error while retrieving meta-information for ActionCLIP 

### ISSUE THREAD

**Issue by CarmelaCalabrese** [open-mmlab/mmaction2#2585]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce GTX 1650
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.8
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.1
OpenCV: 4.8.0
MMEngine: 0.8.1
MMAction2: 1.1.0+
MMCV: 2.0.1

### Describe the bug

Hello everybody,
I am trying to run on the docker image the new ActionCLIP algorithm. I am simply trying to run the demo code but I get an error at the configuration stage, specifically when the code tries to retrieve meta-information. Where am I wrong?

Thank you in advance.

### Reproduces the problem - code sample

import mmengine
from mmaction.utils import register_all_modules
from mmaction.apis import inference_recognizer, init_recognizer

register_all_modules(True)

config_path = 'configs/actionclip_vit-base-p32-res224-clip-pre_1x1x8_k400-rgb.py'
checkpoint_path = 'https://download.openmmlab.com/mmaction/v1.0/projects/actionclip/actionclip_vit-base-p32-res224-clip-pre_1x1x8_k400-rgb/vit-b-32-8f.pth'
template = 'The woman is {}'
labels = ['singing', 'dancing', 'performing']

# Update the labels, the default is the label list of K400.
config = mmengine.Config.fromfile(config_path)
config.model.labels_or_label_file = labels
config.model.template = template

device = "cuda" if torch.cuda.is_available() else "cpu"
model = init_recognizer(config=config, checkpoint=checkpoint_path, device=device)

pred_result = inference_recognizer(model, 'test.mp4')
probs = pred_result.pred_scores.item.cpu().numpy()
print("Label probs:", probs)  # [9.995e-01 5.364e-07 6.666e-04]

### Reproduces the problem - error message

Traceback (most recent call last):
  File "actionCLIP_test.py", line 13, in <module>
    config = mmengine.Config.fromfile(config_path)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 428, in fromfile
    filename, use_predefined_variables, use_environment_variables)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 908, in _file2dict
    raise e
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 851, in _file2dict
    base_cfg_path, filename)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 1233, in _get_cfg_path
    cfg_path = _get_external_cfg_path(package_path, cfg_path)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/utils.py", line 93, in _get_external_cfg_path
    model_cfg = _get_cfg_metainfo(package_path, cfg_file)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/utils.py", line 70, in _get_cfg_metainfo
    cfg_name = model_cfg['Config'].partition('/')[-1]
AttributeError: 'list' object has no attribute 'partition'

### Additional information

The function looks for a string but actually it gets a list, it's like it doesn't see the configuration file (?)

**Comment by cir7** [comment]
Hi, @CarmelaCalabrese Thank you for your feedback. The bug was caused by the invalid format of BSN metafile for MMEngine, which allowed one model to have multiple config files. This resulted in the ‘list’ object in the error message. I have fixed the bug in #2590, and you can check it out. We will merge it as soon as possible.
