### ISSUE TITLE
Iteration Plan - Mar 2021

### ISSUE THREAD

**Issue by dreamerlin** [open-mmlab/mmaction2#674]
Since MMAction2 v0.12.0 has been released, now it's time to plan for the next iteration, i.e. v0.13.0.
This will be a one-month iteration and our focus in this iteration is to support more algorithms and refactor some codes.

**Algorithms**:
- [x] LFB: Lone-Term Feature Bank (https://github.com/open-mmlab/mmaction2/pull/553)
~~Video Transformer researching~~

**Tools**:
- [x] MMCls/TorchVision Backbone registery (https://github.com/open-mmlab/mmaction2/pull/679, #720)
~~Support auto_fp16 using torch.cuda.amp~~

**Misc**:
- [x] CN Tutorial (https://github.com/open-mmlab/mmaction2/pull/665)
- [x] Support CN Readthedocs construction (#716)
~~Entrypoint Refactoring~~ 
~~Unify parameters initilization~~
~~Multi-repo registry usage~~ (#717, #720)

---

### Deferred

- [ ] Entrypoint Refactoring 
- [ ] Unify parameters initilization
- [ ] Multi-repo registry usage (#717, #720)
- [ ] Video Transformer researching
- [ ] Support auto_fp16 using torch.cuda.amp

**Comment by irvingzhang0512** [comment]
+ [ ] mixup
+ [ ] cutmix
+ [ ] recognizers(pytorch/onnxruntime/tensorrt) latency
+ [ ] support onnx/tensorrt model for test.py

**Comment by Bo396543018** [comment]
Hope to add these methods which i found useful for some competitions
 - TEA: Temporal Excitation and Aggregation for Action Recognition (CVPR2020) https://github.com/Phoenix1327/tea-action-recognition
 - PAN: Persistent Appearance Network: https://github.com/zhang-can/PAN-PyTorch
 - TDN: Temporal Difference Networks for Efficient Action Recognition (CVPR 2021) https://github.com/MCG-NJU/TDN

**Comment by congee524** [comment]
> Hope to add these methods which i found useful for some competitions
> 
> * TEA: Temporal Excitation and Aggregation for Action Recognition (CVPR2020) https://github.com/Phoenix1327/tea-action-recognition
> * PAN: Persistent Appearance Network: https://github.com/zhang-can/PAN-PyTorch
> * TDN: Temporal Difference Networks for Efficient Action Recognition (CVPR 2021) https://github.com/MCG-NJU/TDN

Have you trained the models? How does PAN perform on Kinetics?

**Comment by ahkarami** [comment]
Also, hope to add at least one `Temporal Activity Segmentation` method (such as BCN, SSTDA, etc.)
